---
title: "Demographic profile of San Diego County Lawyers"
description: |
  A look at the demographic data of lawyers in San Diego County using U.S. Census data.
author:
- name: Mason Walker
date: "`October 2023`"
output: md_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Demographic profile of lawyers in San Diego County

This analysis explores the demographics of lawyers in San Diego County. The data comes from the U.S. Census Bureau's American Community Survey Public Use Microsample (`PUMS`) dataset. The datasets in this analysis encompass two non-overlapping 5-year ACS files, the 2013-2017 & 2018-2022 files.

More info about the American Community Survey (ACS) can be found on the Census's website [here](https://www.census.gov/programs-surveys/acs).

## Notes
- `pewplots` is used extensively thoughout this analysis to create plots and is a private package and may not be accessible to most users. It it is advised that users turn to `ggplot2` instead.
- To do some of the analysis found in this repository a user will need to obtain an API key from the U.S. Census Bureau. Info how on to obtain an API key can be found on their website [here](https://www.census.gov/data/developers/data-sets.html).




